# Generated by Django 3.2.10 on 2022-06-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_form', '0002_alter_form_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formtemplate',
            old_name='field_name',
            new_name='template_data',
        ),
        migrations.RemoveField(
            model_name='formtemplate',
            name='mandatory',
        ),
        migrations.RemoveField(
            model_name='formtemplate',
            name='options',
        ),
        migrations.RemoveField(
            model_name='formtemplate',
            name='type',
        ),
        migrations.AlterField(
            model_name='form',
            name='file',
            field=models.FileField(upload_to='upload/'),
        ),
    ]
